exports = {
    compacts : [
        {label : "Blista", hash : "blista", prixAchat : 4500, locationJour : 100, link : "vhc/compacts/blista.png"},
        {label : "Brioso", hash : "brioso", prixAchat : 9500, locationJour : 135, link : "vhc/compacts/brioso.png"},
		{label : "Dilettante", hash : "dilettante", prixAchat : 13500, locationJour : 150, link : "vhc/compacts/dilettante.png"},
        {label : "Issi", hash : "issi2", prixAchat : 12000, locationJour : 140, link : "vhc/compacts/issi2.png"},
		{label : "Panto", hash : "panto", prixAchat : 2500, locationJour : 75, link : "vhc/compacts/panto.png"},
        {label : "Prairie", hash : "prairie", prixAchat : 12250, locationJour : 140, link : "vhc/compacts/prairie.png"},
		{label : "Rhapsody", hash : "rhapsody", prixAchat : 6000, locationJour : 110, link : "vhc/compacts/rhapsody.png"}
    ],
    coupes : [
        {label : "Cognoscenti Cabriolet", hash : "cogcabrio", prixAchat : 210000, locationJour : 2100, link : "vhc/coupes/cogcabrio.png"},
        {label : "Exemplar", hash : "exemplar", prixAchat : 160000, locationJour : 1600, link : "vhc/coupes/exemplar.png"},
		{label : "F620", hash : "f620", prixAchat : 185000, locationJour : 1850, link : "vhc/coupes/f620.png"},
        {label : "Felon", hash : "felon", prixAchat : 155000, locationJour : 1550, link : "vhc/coupes/felon.png"},
		{label : "Felon Cabriolet", hash : "felon2", prixAchat : 170000, locationJour : 1700, link : "vhc/coupes/felon2.png"},
        {label : "Jackal", hash : "jackal", prixAchat : 152500, locationJour : 1525, link : "vhc/coupes/jackal.png"},
        {label : "Oracle", hash : "oracle", prixAchat : 145000, locationJour : 1450, link : "vhc/coupes/oracle.png"},
        {label : "Oracle 2", hash : "oracle2", prixAchat : 120000, locationJour : 1200, link : "vhc/coupes/oracle2.png"},
        {label : "Sentinel", hash : "sentinel", prixAchat : 162500, locationJour : 1625, link : "vhc/coupes/sentinel.png"},
        {label : "Sentinel Cabriolet", hash : "sentinel2", prixAchat : 175000, locationJour : 1750, link : "vhc/coupes/sentinel2.png"},
        {label : "Windsor", hash : "windsor", prixAchat : 400000, locationJour : 4000, link : "vhc/coupes/windsor.png"},
        {label : "Windsor Cabriolet", hash : "windsor2", prixAchat : 450000, locationJour : 4500, link : "vhc/coupes/windsor2.png"},
        {label : "Zion", hash : "zion", prixAchat : 160000, locationJour : 1600, link : "vhc/coupes/zion.png"},
        {label : "Zion Cabriolet", hash : "zion2", prixAchat : 172500, locationJour : 1725, link : "vhc/coupes/zion2.png"}
    ],
    velos : [
        {label : "bmx", hash : "bmx", prixAchat : 125, locationJour : 15, link : "vhc/velos/bmx.png"},
        {label : "cruiser", hash : "cruiser", prixAchat : 90, locationJour : 9, link : "vhc/velos/cruiser.png"},
        {label : "fixter", hash : "fixter", prixAchat : 160, locationJour : 20, link : "vhc/velos/fixter.png"},
        {label : "scorcher", hash : "scorcher", prixAchat : 150, locationJour : 18, link : "vhc/velos/scorcher.png"},
        {label : "tribike", hash : "tribike", prixAchat : 175, locationJour : 22, link : "vhc/velos/tribike.png"},
        {label : "tribike2", hash : "tribike2", prixAchat : 175, locationJour : 22, link : "vhc/velos/tribike2.png"},
        {label : "tribike3", hash : "tribike3", prixAchat : 175, locationJour : 22, link : "vhc/velos/tribike3.png"}
    ],
    motos : [
        {label : "Akuma", hash : "akuma", prixAchat : 37500, locationJour : 375, link : "vhc/motos/akuma.png"},
        {label : "Avarus", hash : "avarus", prixAchat : 42500, locationJour : 425, link : "vhc/motos/avarus.png"},
        {label : "Bagger", hash : "bagger", prixAchat : 32500, locationJour : 325, link : "vhc/motos/bagger.png"},
        {label : "Bati", hash : "bati", prixAchat : 67500, locationJour : 675, link : "vhc/motos/bati.png"},
        {label : "Bati RR", hash : "bati2", prixAchat : 70000, locationJour : 700, link : "vhc/motos/bati2.png"},
        {label : "BF 400", hash : "bf400", prixAchat : 50000, locationJour : 500, link : "vhc/motos/bf400.png"},
        {label : "Carbon RS", hash : "carbonrs", prixAchat : 62500, locationJour : 625, link : "vhc/motos/carbonrs.png"},
        {label : "Chimera", hash : "chimera", prixAchat : 60000, locationJour : 600, link : "vhc/motos/chimera.png"},
        {label : "Cliffhanger", hash : "cliffhanger", prixAchat : 57500, locationJour : 575, link : "vhc/motos/cliffhanger.png"},
        {label : "Daemon", hash : "daemon", prixAchat : 40000, locationJour : 400, link : "vhc/motos/daemon.png"},
        {label : "Daemon 2", hash : "daemon2", prixAchat : 45000, locationJour : 450, link : "vhc/motos/daemon2.png"},
        {label : "Defiler", hash : "defiler", prixAchat : 60000, locationJour : 600, link : "vhc/motos/defiler.png"},
        {label : "Deathbike", hash : "deathbike", prixAchat : 45000, locationJour : 450, link : "vhc/motos/deathbike.png"},
        {label : "Diabolus", hash : "diablous", prixAchat : 48000, locationJour : 480, link : "vhc/motos/diablous.png"},
        {label : "Diabolus Street Bike", hash : "diablous2", prixAchat : 49000, locationJour : 490, link : "vhc/motos/diablous2.png"},
        {label : "Double", hash : "double", prixAchat : 61500, locationJour : 615, link : "vhc/motos/double.png"},
        {label : "Enduro", hash : "enduro", prixAchat : 44000, locationJour : 440, link : "vhc/motos/enduro.png"},
        {label : "Esskey", hash : "esskey", prixAchat : 43500, locationJour : 430, link : "vhc/motos/esskey.png"},
        {label : "Faggio", hash : "faggio", prixAchat : 1250, locationJour : 75, link : "vhc/motos/faggio.png"},
        {label : "Faggio 2", hash : "faggio2", prixAchat : 1000, locationJour : 65, link : "vhc/motos/faggio2.png"},
        {label : "Faggio 3", hash : "faggio3", prixAchat : 800, locationJour : 55, link : "vhc/motos/faggio3.png"},
        {label : "FCR", hash : "fcr", prixAchat : 41000, locationJour : 410, link : "vhc/motos/fcr.png"},
        {label : "FCR 2", hash : "fcr2", prixAchat : 42500, locationJour : 425, link : "vhc/motos/fcr2.png"},
        {label : "Gargoyle", hash : "gargoyle", prixAchat : 65000, locationJour : 650, link : "vhc/motos/gargoyle.png"},
        {label : "Hakuchou", hash : "hakuchou", prixAchat : 78000, locationJour : 660, link : "vhc/motos/hakuchou.png"},
        {label : "Hakuchou Sport", hash : "hakuchou2", prixAchat : 110000, locationJour : 1100, link : "vhc/motos/hakuchou2.png"},
        {label : "Hexer", hash : "hexer", prixAchat : 48000, locationJour : 480, link : "vhc/motos/hexer.png"},
        {label : "Innovation", hash : "innovation", prixAchat : 82500, locationJour : 825, link : "vhc/motos/innovation.png"},
        {label : "Lectro", hash : "lectro", prixAchat : 39500, locationJour : 395, link : "vhc/motos/lectro.png"},
        {label : "Manchez", hash : "manchez", prixAchat : 42500, locationJour : 425, link : "vhc/motos/manchez.png"},
        {label : "Nemesis", hash : "nemesis", prixAchat : 41000, locationJour : 410, link : "vhc/motos/nemesis.png"},
        {label : "NightBlade", hash : "nightblade", prixAchat : 76000, locationJour : 760, link : "vhc/motos/nightblade.png"},
        {label : "PCJ", hash : "pcj", prixAchat : 35000, locationJour : 350, link : "vhc/motos/pcj.png"},
        {label : "Ruffian", hash : "ruffian", prixAchat : 38500, locationJour : 385, link : "vhc/motos/ruffian.png"},
        {label : "Sanchez", hash : "sanchez2", prixAchat : 16000, locationJour : 400, link : "vhc/motos/sanchez2.png"},
        {label : "Sanctus", hash : "sanctus", prixAchat : 160000, locationJour : 1600, link : "vhc/motos/sanctus.png"},
        {label : "Sovereign", hash : "sovereign", prixAchat : 36000, locationJour : 360, link : "vhc/motos/sovereign.png"},
        {label : "Trust", hash : "trust", prixAchat : 51500, locationJour : 515, link : "vhc/motos/thrust.png"},
        {label : "Vader", hash : "vader", prixAchat : 36500, locationJour : 365, link : "vhc/motos/vader.png"},
        {label : "Vindicator", hash : "vindicator", prixAchat : 57500, locationJour : 575, link : "vhc/motos/vindicator.png"},
        {label : "Vortex", hash : "vortex", prixAchat : 68500, locationJour : 685, link : "vhc/motos/vortex.png"},
        {label : "Wolfsbane", hash : "wolfsbane", prixAchat : 44000, locationJour : 440, link : "vhc/motos/wolfsbane.png"},
        {label : "Zombie", hash : "zombiea", prixAchat : 46000, locationJour : 460, link : "vhc/motos/zombiea.png"},
        {label : "Zombie 2", hash : "zombieb", prixAchat : 47000, locationJour : 470, link : "vhc/motos/zombieb.png"}
    ],
    muscles : [
        {label : "Blade", hash : "blade", prixAchat : 70000, locationJour : 700, link : "vhc/muscles/blade.png"},
        {label : "Buccaneer", hash : "buccaneer", prixAchat : 77500, locationJour : 775, link : "vhc/muscles/buccaneer.png"},
        {label : "Buccaneer2", hash : "buccaneer2", prixAchat : 80000, locationJour : 800, link : "vhc/muscles/buccaneer2.png"},
        {label : "Chino", hash : "chino", prixAchat : 75000, locationJour : 750, link : "vhc/muscles/chino.png"},
        {label : "Chino2", hash : "chino2", prixAchat : 76500, locationJour : 765, link : "vhc/muscles/chino2.png"},
        {label : "Clique", hash : "clique", prixAchat : 125000, locationJour : 1250, link : "vhc/muscles/clique.png"},
        {label : "Coquette3", hash : "coquette3", prixAchat : 170000, locationJour : 1700, link : "vhc/muscles/coquette3.png"},
        {label : "Deviant", hash : "deviant", prixAchat : 165000, locationJour : 1650, link : "vhc/muscles/deviant.png"},
        {label : "Dominator", hash : "dominator", prixAchat : 115000, locationJour : 1150, link : "vhc/muscles/dominator.png"},
        {label : "Dominator2", hash : "dominator2", prixAchat : 125000, locationJour : 1250, link : "vhc/muscles/dominator2.png"},
        {label : "Dominator3", hash : "dominator3", prixAchat : 210000, locationJour : 2100, link : "vhc/muscles/dominator3.png"},
        {label : "Dukes", hash : "dukes", prixAchat : 72500, locationJour : 725, link : "vhc/muscles/dukes.png"},
        {label : "Faction", hash : "faction", prixAchat : 62000, locationJour : 620, link : "vhc/muscles/faction.png"},
        {label : "Faction2", hash : "faction2", prixAchat : 77500, locationJour : 775, link : "vhc/muscles/faction2.png"},
        {label : "Gauntlet", hash : "gauntlet", prixAchat : 95000, locationJour : 950, link : "vhc/muscles/gauntlet.png"},
        {label : "Gauntlet2", hash : "gauntlet2", prixAchat : 100000, locationJour : 1000, link : "vhc/muscles/gauntlet2.png"},
        {label : "Hotknife", hash : "hotknife", prixAchat : 285000, locationJour : 2850, link : "vhc/muscles/hotknife.png"},
        {label : "Impaler", hash : "impaler", prixAchat : 70500, locationJour : 705, link : "vhc/muscles/impaler.png"},
        {label : "Impaler3", hash : "impaler3", prixAchat : 71000, locationJour : 710, link : "vhc/muscles/impaler3.png"},
        {label : "Imperator", hash : "imperator", prixAchat : 120000, locationJour : 1200, link : "vhc/muscles/imperator.png"},
        {label : "Moonbeam", hash : "moonbeam", prixAchat : 115000, locationJour : 1500, link : "vhc/muscles/moonbeam.png"},
        {label : "Moonbeam2", hash : "moonbeam2", prixAchat : 145000, locationJour : 1450, link : "vhc/muscles/moonbeam2.png"},
        {label : "Nightshade", hash : "nightshade", prixAchat : 135000, locationJour : 1350, link : "vhc/muscles/nightshade.png"},
        {label : "Phoenix", hash : "phoenix", prixAchat : 82500, locationJour : 825, link : "vhc/muscles/phoenix.png"},
        {label : "Picador", hash : "picador", prixAchat : 55000, locationJour : 550, link : "vhc/muscles/picador.png"},
        {label : "Ratloader2", hash : "ratloader2", prixAchat : 65000, locationJour : 650, link : "vhc/muscles/ratloader2.png"},
        {label : "Ruiner", hash : "ruiner", prixAchat : 75000, locationJour : 750, link : "vhc/muscles/ruiner.png"},
        {label : "Sabregt", hash : "sabregt", prixAchat : 77000, locationJour : 770, link : "vhc/muscles/sabregt.png"},
        {label : "Sabregt2", hash : "sabregt2", prixAchat : 82500, locationJour : 825, link : "vhc/muscles/sabregt2.png"},
        {label : "Slamvan3", hash : "slamvan3", prixAchat : 85000, locationJour : 850, link : "vhc/muscles/slamvan3.png"},
        {label : "Stalion", hash : "stalion", prixAchat : 74000, locationJour : 740, link : "vhc/muscles/stalion.png"},
        {label : "Stalion2", hash : "stalion2", prixAchat : 75000, locationJour : 750, link : "vhc/muscles/stalion2.png"},
        {label : "Tampa", hash : "tampa", prixAchat : 95000, locationJour : 950, link : "vhc/muscles/tampa.png"},
        {label : "Tulip", hash : "tulip", prixAchat : 98000, locationJour : 980, link : "vhc/muscles/tulip.png"},
        {label : "Vamos", hash : "vamos", prixAchat : 90000, locationJour : 900, link : "vhc/muscles/vamos.png"},
        {label : "Vigero", hash : "vigero", prixAchat : 75000, locationJour : 750, link : "vhc/muscles/vigero.png"},
        {label : "Virgo", hash : "virgo", prixAchat : 77000, locationJour : 770, link : "vhc/muscles/virgo.png"},
        {label : "Virgo2", hash : "virgo2", prixAchat : 82500, locationJour : 825, link : "vhc/muscles/virgo2.png"},
        {label : "Virgo3", hash : "virgo3", prixAchat : 83000, locationJour : 830, link : "vhc/muscles/virgo3.png"},
        {label : "Voodoo", hash : "voodoo", prixAchat : 60000, locationJour : 600, link : "vhc/muscles/voodoo.png"},
        {label : "Yosemite", hash : "yosemite", prixAchat : 70000, locationJour : 700, link : "vhc/muscles/yosemite.png"}

    ],
    offroad : [
        {label : "Bfinject", hash : "bfinjection", prixAchat : 25000, locationJour : 250, link : "vhc/offroad/bfinject.png"},
        {label : "Bifta", hash : "bifta", prixAchat : 22500, locationJour : 225, link : "vhc/offroad/bifta.png"},
        {label : "Blazer", hash : "blazer", prixAchat : 14000, locationJour : 140, link : "vhc/offroad/blazer.png"},
        {label : "Blazer4", hash : "blazer4", prixAchat : 16500, locationJour : 165, link : "vhc/offroad/blazer4.png"},
        {label : "Brawler", hash : "brawler", prixAchat : 75000, locationJour : 750, link : "vhc/offroad/brawler.png"},
        {label : "Dubsta3", hash : "dubsta3", prixAchat : 400000, locationJour : 4000, link : "vhc/offroad/dubsta3.png"},
        {label : "Kalahari", hash : "kalahari", prixAchat : 6500, locationJour : 275, link : "vhc/offroad/kalahari.png"},
        {label : "Mesa3", hash : "mesa3", prixAchat : 180000, locationJour : 1800, link : "vhc/offroad/mesa3.png"},
        {label : "Rancherxl", hash : "rancherxl", prixAchat : 80000, locationJour : 800, link : "vhc/offroad/rancherxl.png"},
        {label : "Rebel2", hash : "rebel2", prixAchat : 120000, locationJour : 1200, link : "vhc/offroad/rebel2.png"},
        {label : "Riata", hash : "riata", prixAchat : 220000, locationJour : 2200, link : "vhc/offroad/riata.png"},
        {label : "Sandking", hash : "sandking", prixAchat : 195000, locationJour : 1950, link : "vhc/offroad/sandking.png"},
        {label : "Sandking2", hash : "sandking2", prixAchat : 205000, locationJour : 2050, link : "vhc/offroad/sandking2.png"},
        {label : "Kamacho", hash : "kamacho", prixAchat : 90000, locationJour : 900, link : "vhc/offroad/kamacho.png"}

    ],
    suvs : [
        {label : "Baller", hash : "baller", prixAchat : 90000, locationJour : 900, link : "vhc/suvs/baller.png"},
        {label : "Baller2", hash : "baller2", prixAchat : 120000, locationJour : 1200, link : "vhc/suvs/baller2.png"},
        {label : "Baller3", hash : "baller3", prixAchat : 135000, locationJour : 1350, link : "vhc/suvs/baller3.png"},
        {label : "Baller4", hash : "baller4", prixAchat : 150000, locationJour : 1500, link : "vhc/suvs/baller4.png"},
        {label : "Bjxl", hash : "bjxl", prixAchat : 85000, locationJour : 850, link : "vhc/suvs/bjxl.png"},
        {label : "Cavalcade", hash : "calvalcade", prixAchat : 95000, locationJour : 950, link : "vhc/suvs/cavalcade.png"},
        {label : "Cavalcade2", hash : "calvalcade2", prixAchat : 105000, locationJour : 1050, link : "vhc/suvs/cavalcade2.png"},
        {label : "Contender", hash : "contender", prixAchat : 200000, locationJour : 2000, link : "vhc/suvs/contender.png"},
        {label : "Dubsta", hash : "dusta", prixAchat : 100000, locationJour : 1000, link : "vhc/suvs/dubsta.png"},
        {label : "Dusta2", hash : "dusta2", prixAchat : 120000, locationJour : 1200, link : "vhc/suvs/dubsta2.png"},
        {label : "Fq2", hash : "fq2", prixAchat : 65000, locationJour : 650, link : "vhc/suvs/fq2.png"},
        {label : "Granger", hash : "granger", prixAchat : 160000, locationJour : 1600, link : "vhc/suvs/granger.png"},
        {label : "Gresley", hash : "gresley", prixAchat : 80000, locationJour : 800, link : "vhc/suvs/gresley.png"},
        {label : "Habanero", hash : "habanero", prixAchat : 50000, locationJour : 500, link : "vhc/suvs/habanero.png"},
        {label : "Huntley", hash : "huntley", prixAchat : 82500, locationJour : 825, link : "vhc/suvs/huntley.png"},
        {label : "Landstalker", hash : "landstalker", prixAchat : 80000, locationJour : 800, link : "vhc/suvs/landstalker.png"},
        {label : "Mesa", hash : "mesa", prixAchat : 67500, locationJour : 675, link : "vhc/suvs/mesa.png"},
        {label : "Patriot", hash : "patriot", prixAchat : 125000, locationJour : 1250, link : "vhc/suvs/patriot.png"},
        {label : "Radi", hash : "radi", prixAchat : 67500, locationJour : 675, link : "vhc/suvs/radi.png"},
        {label : "Rocoto", hash : "rocoto", prixAchat : 85000, locationJour : 850, link : "vhc/suvs/rocoto.png"},
        {label : "Seminole", hash : "seminole", prixAchat : 77500, locationJour : 775, link : "vhc/suvs/seminole.png"},
        {label : "Serrano", hash : "serrano", prixAchat : 67500, locationJour : 675, link : "vhc/suvs/serrano.png"},
        {label : "Toros", hash : "toros", prixAchat : 250000, locationJour : 2500, link : "vhc/suvs/toros.png"},
        {label : "Xls", hash : "xls", prixAchat : 180000, locationJour : 1800, link : "vhc/suvs/xls.png"}
    
    ],    
    sedans : [
        {label : "Asea", hash : "asea", prixAchat : 25000, locationJour : 250, link : "vhc/sedans/asea.png"},
        {label : "Asterope", hash : "asterope", prixAchat : 27000, locationJour : 270, link : "vhc/sedans/asterope.png"},
        {label : "Cog55", hash : "cog55", prixAchat : 75000, locationJour : 750, link : "vhc/sedans/cog55.png"},
        {label : "Cognoscenti", hash : "cognoscenti", prixAchat : 80000, locationJour : 800, link : "vhc/sedans/cognoscenti.png"},
        {label : "Emperor", hash : "emperor", prixAchat : 15000, locationJour : 150, link : "vhc/sedans/emperor.png"},
        {label : "Fugitive", hash : "fugitive", prixAchat : 30000, locationJour : 300, link : "vhc/sedans/fugitive.png"},
        {label : "Glendale", hash : "glendale", prixAchat : 29000, locationJour : 290, link : "vhc/sedans/glendale.png"},
        {label : "Ingot", hash : "ingot", prixAchat : 16000, locationJour : 190, link : "vhc/sedans/ingot.png"},
        {label : "Intruder", hash : "intruder", prixAchat : 23000, locationJour : 230, link : "vhc/sedans/intruder.png"},
        {label : "Premier", hash : "prermier", prixAchat : 25500, locationJour : 255, link : "vhc/sedans/premier.png"},
        {label : "Primo", hash : "primo", prixAchat : 19000, locationJour : 190, link : "vhc/sedans/primo.png"},
        {label : "Primo2", hash : "primo2", prixAchat : 25000, locationJour : 250, link : "vhc/sedans/primo2.png"},
        {label : "Regina", hash : "regina", prixAchat : 20000, locationJour : 200, link : "vhc/sedans/regina.png"},
        {label : "Schafter2", hash : "schafter2", prixAchat : 41000, locationJour : 410, link : "vhc/sedans/schafter2.png"},
        {label : "Stafford", hash : "stafford", prixAchat : 110000, locationJour : 1100, link : "vhc/sedans/stafford.png"},
        {label : "Stanier", hash : "stanier", prixAchat : 19000, locationJour : 190, link : "vhc/sedans/stanier.png"},
        {label : "Stratum", hash : "stratum", prixAchat : 17000, locationJour : 170, link : "vhc/sedans/stratum.png"},
        {label : "Stretch", hash : "stretch", prixAchat : 300000, locationJour : 3000, link : "vhc/sedans/stretch.png"},
        {label : "Super Diamond", hash : "superd", prixAchat : 100000, locationJour : 1000, link : "vhc/sedans/superd.png"},
        {label : "Surge", hash : "surge", prixAchat : 30000, locationJour : 300, link : "vhc/sedans/surge.png"},
        {label : "Tailgater", hash : "tailgater", prixAchat : 32000, locationJour : 320, link : "vhc/sedans/tailgater.png"},
        {label : "Warrener", hash : "warrener", prixAchat : 29000, locationJour : 290, link : "vhc/sedans/warrener.png"},
        {label : "Washington", hash : "washigton", prixAchat : 24000, locationJour : 240, link : "vhc/sedans/washington.png"}

    ],  
    sports : [
        {label : "Alpha", hash : "alpha", prixAchat : 90000, locationJour : 900, link : "vhc/sports/alpha.png"},
        {label : "Banshee", hash : "banshee", prixAchat : 115000, locationJour : 1150, link : "vhc/sports/banshee.png"},
        {label : "Bestiagts", hash : "bestiagts", prixAchat : 140000, locationJour : 1400, link : "vhc/sports/bestiagts.png"},
        {label : "Blista2", hash : "blista2", prixAchat : 52500, locationJour : 525, link : "vhc/sports/blista2.png"},
        {label : "Buffalo", hash : "buffalo", prixAchat : 95000, locationJour : 950, link : "vhc/sports/buffalo.png"},
        {label : "Buffalo2", hash : "buffalo2", prixAchat : 110000, locationJour : 1100, link : "vhc/sports/buffalo2.png"},
        {label : "Carbonizare", hash : "carbonizzare", prixAchat : 150000, locationJour : 1500, link : "vhc/sports/carbonizzare.png"},
        {label : "Comet2", hash : "comet2", prixAchat : 120000, locationJour : 1200, link : "vhc/sports/comet2.png"},
        {label : "Comet3", hash : "comet3", prixAchat : 160000, locationJour : 1600, link : "vhc/sports/comet3.png"},
        {label : "Coquette", hash : "coquette", prixAchat : 150000, locationJour : 1500, link : "vhc/sports/coquette.png"},
        {label : "Elegy", hash : "elegy", prixAchat : 157500, locationJour : 1575, link : "vhc/sports/elegy.png"},
        {label : "Elegy2", hash : "elegy2", prixAchat : 125000, locationJour : 1250, link : "vhc/sports/elegy2.png"},
        {label : "Feltzer2", hash : "feltzer2", prixAchat : 130000, locationJour : 1300, link : "vhc/sports/feltzer2.png"},
        {label : "Furoregt", hash : "furoregt", prixAchat : 155000, locationJour : 1550, link : "vhc/sports/furoregt.png"},
        {label : "Fusilade", hash : "fusilade", prixAchat : 80000, locationJour : 800, link : "vhc/sports/fusilade.png"},
        {label : "Futo", hash : "futo", prixAchat : 50000, locationJour : 500, link : "vhc/sports/futo.png"},
        {label : "Italigto", hash : "italigto", prixAchat : 200000, locationJour : 2000, link : "vhc/sports/italigto.png"},
        {label : "Jester", hash : "jester", prixAchat : 190000, locationJour : 1900, link : "vhc/sports/jester.png"},
        {label : "Khamelion", hash : "khamelion", prixAchat : 155000, locationJour : 1550, link : "vhc/sports/khamelion.png"},
        {label : "Kuruma", hash : "kuruma", prixAchat : 100000, locationJour : 1000, link : "vhc/sports/kuruma.png"},
        {label : "Lynx", hash : "lynx", prixAchat : 140000, locationJour : 1400, link : "vhc/sports/lynx.png"},
        {label : "Massacro", hash : "massacro", prixAchat : 125000, locationJour : 1250, link : "vhc/sports/massacro.png"},
        {label : "Neon", hash : "neon", prixAchat : 190000, locationJour : 1900, link : "vhc/sports/neon.png"},
        {label : "Ninef", hash : "ninef", prixAchat : 165000, locationJour : 1650, link : "vhc/sports/ninef.png"},
        {label : "Ninef2", hash : "ninef2", prixAchat : 170000, locationJour : 1700, link : "vhc/sports/ninef2.png"},
        {label : "Pariah", hash : "pariah", prixAchat : 132500, locationJour : 1350, link : "vhc/sports/pariah.png"},
        {label : "Penumbra", hash : "penumbra", prixAchat : 87500, locationJour : 875, link : "vhc/sports/penumbra.png"},
        {label : "Raiden", hash : "raiden", prixAchat : 97500, locationJour : 975, link : "vhc/sports/raiden.png"},
        {label : "Rapidgt", hash : "rapidgt", prixAchat : 92500, locationJour : 925, link : "vhc/sports/rapidgt.png"},
        {label : "Rapidgt2", hash : "rapidgt2", prixAchat : 98000, locationJour : 980, link : "vhc/sports/rapidgt2.png"},
        {label : "Raptor", hash : "raptor", prixAchat : 15000, locationJour : 150, link : "vhc/sports/raptor.png"},
        {label : "Revolter", hash : "revolter", prixAchat : 130000, locationJour : 1300, link : "vhc/sports/revolter.png"},
        {label : "Schafter3", hash : "schafter3", prixAchat : 75000, locationJour : 750, link : "vhc/sports/schafter3.png"},
        {label : "Schafter4", hash : "schafter4", prixAchat : 95000, locationJour : 950, link : "vhc/sports/schafter4.png"},
        {label : "Schlagen", hash : "schlagen", prixAchat : 230000, localtionJour : 2300, link : "vhc/sports/schlagen.png"},
        {label : "Schwarzer", hash : "schwarzer", prixAchat : 74000, locationJour : 740, link : "vhc/sports/schwarzer.png"},
        {label : "Sentinel3", hash : "sentinel3", prixAchat : 102500, locationJour : 1250, link : "vhc/sports/sentinel3.png"},
        {label : "Seven70", hash : "seven70", prixAchat : 180000, locationJour : 1800, link : "vhc/sports/seven70.png"},
        {label : "Specter", hash : "specter", prixAchat : 152500, locationJour : 1550, link : "vhc/sports/specter.png"},
        {label : "Specter2", hash : "specter2", prixAchat : 162500, locationJour : 1650, link : "vhc/sports/specter2.png"},
        {label : "Sultan", hash : "sultan", prixAchat : 80000, locationJour : 800, link : "vhc/sports/sultan.png"},
        {label : "Surano", hash : "surano", prixAchat : 112500, locationJour : 1125, link : "vhc/sports/surano.png"},
        {label : "Tropos", hash : "tropos", prixAchat : 130000, locationJour : 1300, link : "vhc/sports/tropos.png"},
        {label : "Verlierer2", hash : "verlierer2", prixAchat : 160000, locationJour : 1600, link : "vhc/sports/verlierer2.png"}

    ],
    sportsclassic : [
        {label : "Btype", hash : "btype", prixAchat : 240000, locationJour : 2400, link : "vhc/sportsclassic/btype.png"},
        {label : "Btype3", hash : "btype3", prixAchat : 280000, locationJour : 2800, link : "vhc/sportsclassic/btype3.png"},
        {label : "Casco", hash : "casco", prixAchat : 260000, locationJour : 2600, link : "vhc/sportsclassic/casco.png"},
        {label : "Cheetah2", hash : "cheetah2", prixAchat : 350000, locationJour : 3500, link : "vhc/sportsclassic/cheetah2.png"},
        {label : "Coquette2", hash : "coquette2", prixAchat : 300000, locationJour : 3000, link : "vhc/sportsclassic/coquette2.png"},
        {label : "Feltzer3", hash : "feltzer3", prixAchat : 315000, locationJour : 3150, link : "vhc/sportsclassic/feltzer3.png"},
        {label : "Gt500", hash : "gt500", prixAchat : 220000, locationJour : 2200, link : "vhc/sportsclassic/gt500.png"},
        {label : "Infernus2", hash : "infernus2", prixAchat : 325000, locationJour : 3250, link : "vhc/sportsclassic/infernus2.png"},
        {label : "Mamba", hash : "mamba", prixAchat : 305000, locationJour : 3050, link : "vhc/sportsclassic/mamba.png"},
        {label : "Manana", hash : "manana", prixAchat : 25000, locationJour : 250, link : "vhc/sportsclassic/manana.png"},
        {label : "Monroe", hash : "monroe", prixAchat : 225000, locationJour : 2250, link : "vhc/sportsclassic/monroe.png"},
        {label : "Peyote", hash : "peyote", prixAchat : 32000, locationJour : 320, link : "vhc/sportsclassic/peyote.png"},
        {label : "Pigalle", hash : "pigalle", prixAchat : 46000, locationJour : 460, link : "vhc/sportsclassic/pigalle.png"},
        {label : "Rapidgt3", hash : "rapidgt3", prixAchat : 175000, locationJour : 1750, link : "vhc/sportsclassic/rapidgt3.png"},
        {label : "Retinue", hash : "retinue", prixAchat : 75000, locationJour : 750, link : "vhc/sportsclassic/retinue.png"},
        {label : "Savestra", hash : "savestra", prixAchat : 95000, locationJour : 950, link : "vhc/sportsclassic/savestra.png"},
        {label : "Stinger", hash : "stinger", prixAchat : 230000, locationJour : 2300, link : "vhc/sportsclassic/stinger.png"},
        {label : "Stingergt", hash : "stingergt", prixAchat : 345000, locationJour : 3450, link : "vhc/sportsclassic/stingergt.png"},
        {label : "Stromberg", hash : "stromberg", prixAchat : 305000, locationJour : 3050, link : "vhc/sportsclassic/stromberg.png"},
        {label : "Swinger", hash : "swinger", prixAchat : 350000, locationJour : 3500, link : "vhc/sportsclassic/swinger.png"},
        {label : "Torero", hash : "torero", prixAchat : 320000, locationJour : 3200, link : "vhc/sportsclassic/torero.png"},
        {label : "Tornado", hash : "tornado", prixAchat : 25000, locationJour : 250, link : "vhc/sportsclassic/tornado.png"},
        {label : "Tornado2", hash : "tornado2", prixAchat : 28000, locationJour : 280, link : "vhc/sportsclassic/tornado2.png"},
        {label : "Turismo2", hash : "turismo2", prixAchat : 380000, locationJour : 3800, link : "vhc/sportsclassic/turismo2.png"},
        {label : "Viseris", hash : "viseris", prixAchat : 290000, locationJour : 2900, link : "vhc/sportsclassic/viseris.png"},
        {label : "Ztype", hash : "ztype", prixAchat : 400000, locationJour : 4000, link : "vhc/sportsclassic/ztype.png"}

    ],
    super : [
      {label : "Adder", hash : "adder", prixAchat : 700000, locationJour : 7000, link : "vhc/super/adder.png"},
      {label : "Autarch", hash : "autarch", prixAchat : 1000000, locationJour : 10000, link : "vhc/super/autarch.png"},
      {label : "Banshee2", hash : "banshee2", prixAchat : 450000, locationJour : 4500, link : "vhc/super/banshee2.png"},
      {label : "Bullet", hash : "bullet", prixAchat : 400000, locationJour : 4000, link : "vhc/super/bullet.png"},
      {label : "Cheetah", hash : "cheetah", prixAchat : 900000, locationJour : 9000, link : "vhc/super/cheetah.png"},
      {label : "Cyclone", hash : "cyclone", prixAchat : 650000, locationJour : 6500, link : "vhc/super/cyclone.png"},
      {label : "Entityxf", hash : "entityxf", prixAchat : 950000, locationJour : 9500, link : "vhc/super/entityxf.png"},
      {label : "Fmj", hash : "fmj", prixAchat : 975000, locationJour : 9750, link : "vhc/super/fmj.png"},
      {label : "Gp1", hash : "gp1", prixAchat : 725000, locationJour : 7250, link : "vhc/super/gp1.png"},
      {label : "Infernus", hash : "infernus", prixAchat : 500000, locationJour : 5000, link : "vhc/super/infernus.png"},
      {label : "Italigtb", hash : "italigtb", prixAchat : 875000, locationJour : 8750, link : "vhc/super/italigtb.png"},
      {label : "Italigtb2", hash : "italigtb2", prixAchat : 915000, locationJour : 9150, link : "vhc/super/italigtb2.png"}, 
      {label : "Nero", hash : "nero", prixAchat : 800000, locationJour : 8000, link : "vhc/super/nero.png"},
      {label : "Nero2", hash : "nero2", prixAchat : 875000, locationJour : 8750, link : "vhc/super/nero2.png"},
      {label : "Osiris", hash : "osiris", prixAchat : 750000, locationJour : 7500, link : "vhc/super/osiris.png"},
      {label : "Penetrator", hash : "penetrator", prixAchat : 595000, locationJour : 5950, link : "vhc/super/penetrator.png"},
      {label : "Pfister811", hash : "pfister811", prixAchat : 720000, locationJour : 7200, link : "vhc/super/pfister811.png"},
      {label : "X80 Proto", hash : "prototipo", prixAchat : 3500000, locationJour : 35000, link : "vhc/super/prototipo.png"},
      {label : "Reaper", hash : "reaper", prixAchat : 930000, locationJour : 9300, link : "vhc/super/reaper.png"},
      {label : "Sc1", hash : "sc1", prixAchat : 550000, locationJour : 5500, link : "vhc/super/sc1.png"},
      {label : "ETR1", hash : "sheava", prixAchat : 735000, locationJour : 7350, link : "vhc/super/sheava.png"},
      {label : "Sultanrs", hash : "sultanrs", prixAchat : 350000, locationJour : 3500, link : "vhc/super/sultanrs.png"},
      {label : "T20", hash : "t20", prixAchat : 980000, locationJour : 9800, link : "vhc/super/t20.png"},
      {label : "Tempesta", hash : "tempesta", prixAchat : 915000, locationJour : 9150, link : "vhc/super/tempesta.png"},
      {label : "Turismo R", hash : "turismor", prixAchat : 935000, locationJour : 9350, link : "vhc/super/turismor.png"},
      {label : "Tyrus", hash : "tyrus", prixAchat : 895000, locationJour : 8950, link : "vhc/super/tyrus.png"},
      {label : "Vacca", hash : "vacca", prixAchat : 925000, locationJour : 9250, link : "vhc/super/vacca.png"},
      {label : "Vagner", hash : "vagner", prixAchat : 1050000, locationJour : 10500, link : "vhc/super/vagner.png"},  
      {label : "Visione", hash : "visione", prixAchat : 1100000, locationJour : 11000, link : "vhc/super/visione.png"},
      {label : "Voltic", hash : "voltic", prixAchat : 635000, locationJour : 6350, link : "vhc/super/voltic.png"},
      {label : "xA21", hash : "xa21", prixAchat : 805000, locationJour : 8050, link : "vhc/super/xa21.png"},
      {label : "Zentorno", hash : "zentorno", prixAchat : 1200000, locationJour : 12000, link : "vhc/super/zentorno.png"}

    ],
    vans : [
        {label : "Bison", hash : "Bison", prixAchat : 75000, locationJour : 750, link : "vhc/vans/bison.png"},
        {label : "Bobcatxl", hash : "bobcatxl", prixAchat : 72500, locationJour : 700, link : "vhc/vans/bobcatxl.png"},
        {label : "Burrito3", hash : "burrito", prixAchat : 62500, locationJour : 625, link : "vhc/vans/burrito3.png"},
        {label : "Camper", hash : "camper", prixAchat : 50000, locationJour : 500, link : "vhc/vans/camper.png"},
        {label : "Gburrito", hash : "gburrito", prixAchat : 95000, locationJour : 950, link : "vhc/vans/gburrito.png"},
        {label : "Gburrito2", hash : "gburrito2", prixAchat : 100000, locationJour : 1000, link : "vhc/vans/gburrito2.png"},
        {label : "Journey", hash : "journey", prixAchat : 30000, locationJour : 300, link : "vhc/vans/journey.png"},
        {label : "Minivan", hash : "minivan", prixAchat : 68000, locationJour : 680, link : "vhc/vans/minivan.png"},
        {label : "Minivan2", hash : "minivan2", prixAchat : 71500, locationJour : 725, link : "vhc/vans/minivan2.png"},
        {label : "Paradise", hash : "paradise", prixAchat : 63500, locationJour : 635, link : "vhc/vans/paradise.png"},
        {label : "Pony", hash : "Pony", prixAchat : 60000, locationJour : 600, link : "vhc/vans/pony.png"},
        {label : "Pony2", hash : "pony2", prixAchat : 61500, locationJour : 615, link : "vhc/vans/pony2.png"},
        {label : "Rumpo", hash : "rumpo", prixAchat : 63000, locationJour : 630, link : "vhc/vans/rumpo.png"},
        {label : "rumpo2", hash : "rumpo2", prixAchat : 63000, locationJour : 630, link : "vhc/vans/rumpo2.png"},
        {label : "rumpo Custom", hash : "rumpo3", prixAchat : 75000, locationJour : 700, link : "vhc/vans/rumpo3.png"},
        {label : "Speedo", hash : "speedo", prixAchat : 65000, locationJour : 650, link : "vhc/vans/speedo.png"},
        {label : "Surfer", hash : "surfer", prixAchat : 45000, locationJour : 450, link : "vhc/vans/surfer.png"},
        {label : "Youga", hash : "youga", prixAchat : 67500, locationJour : 675, link : "vhc/vans/youga.png"},
        {label : "Youga2", hash : "youga2", prixAchat : 70000, locationJour : 700, link : "vhc/vans/youga2.png"}
    ]

}   

        
